---
abstract: 'Google Federated Login module - see http://code.google.com/apis/accounts/docs/OpenID.html'
author:
  - 'Glenn Fowler <cebjyre@cpan.org>'
build_requires:
  CGI: 0
  Test::Mock::LWP: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200005, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-FederatedLogin
requires:
  Carp: 0
  LWP::UserAgent: 0
  Moose: 0.51
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  URI::Escape: 0
  XML::Twig: 0
resources:
  repository: http://github.com/cebjyre/Net-Google-FederatedLogin
version: 0.6.0
